kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.12
    commands:
      - go install -mod=vendor golang.org/x/lint/golint
      - go vet -mod=vendor ./...
      - go test -mod=vendor -v ./...
      - golint -set_exit_status `find . -type d -not -path "./vendor*" -not -path "./.git*"`
    settings:
      environment:
        - GO111MODULE=on

  - name: build
    image: plugins/docker
    settings:
      repo: registry.megpoid.xyz/goforward
      tags: latest
      mirror: http://mirror:5000
      build_args:
        - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
        - BUILD_COMMIT_SHORT=${DRONE_COMMIT_SHA:0:8}
      registry: registry.megpoid.xyz
      username: admin
      password:
        from_secret: docker_password

trigger:
  branch:
    - master
