---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.51.2
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...
    when:
      event:
        exclude:
          - tag
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: build
    image: ghcr.io/codestation/drone-docker
    settings:
      cache:
        - registry.megpoid.dev/codestation/goforward:${DRONE_BRANCH}-cache
      repos:
        - registry.megpoid.dev/codestation/swarm-updater
      tags: latest
      registry: registry.megpoid.dev
      platforms:
        - linux/amd64
        - linux/arm64
      buildkit: true
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - goproxy
    environment:
      goproxy:
        from_secret: goproxy_url

  - name: update
    image: plugins/webhook
    settings:
      urls: http://updater:8000/apis/swarm/v1/update
      token_value:
        from_secret: updater_apikey
      template: |
        {
          "images": [
            "registry.megpoid.dev/codestation/swarm-updater"
          ]
        }

trigger:
  branch:
    - master
